name: End to end Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./tests/end-to-end
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@378c8285a4eaf12899d11bea686a763e906956af
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: ./tests/end-to-end/package-lock.json
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium
    - name: build sqlpage
      run: cargo build
      working-directory: ./examples/official-site
    - name: start official site and wait for it to be ready
      timeout-minutes: 1
      run: |
        cargo run 2>/tmp/stderrlog &
        tail -f /tmp/stderrlog | grep -q "started successfully"
      working-directory: ./examples/official-site
    - name: Run Playwright tests
      run: npx playwright test
    - name: show server logs
      if: failure()
      run: cat /tmp/stderrlog
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ./tests/end-to-end/playwright-report/
        retention-days: 30
[![End to end Tests](https://github.com/L40L44/SQLPage/actions/workflows/playwright.yml/badge.svg)](https://github.com/L40L44/SQLPage/actions/workflows/playwright.yml)
